openapi: 3.0.0
info:
  title: Ad Serving API
  version: '1.0'
  contact:
    name: Content.ad Support
    url: 'https://help.content.ad'
    email: support@content.ad
  description: |-
    The Content.ad Widget API is a flexible alternative to the standard JavaScript implementation. Widget results are returned as a JSON object, and settings (number of ads, type of content, etc.) are managed in the widget section of the Content.ad admin.

    The Widget API can be accessed either by using the in-browser instalation code, or by accessing this API directly. If you are accessing this API directly, pass the widget parameters appropriate to your use case to the GetWidget endpoint. If you'd like to reproduce the in-browser experience, you can either use our standard installation code provided in the Contetn.ad UI, or you can call the widget2 endpoint directly, followed by the GetWidget endpoint.

    ## Setting Up the API Call

    Set up a widget in the Content.ad admin. Performance reports can be broken out by widget or domain. If the domain is new, it must be approved by the Content.ad team before showing sponsored content.

    Copy the parameters in the installation code labeled “id” and “d”. These are your unique widget ID and unique domain ID, respectively. These are not the same as the Widget ID and Domain ID in the user interface. They are the long strings in the widget installation code.

    Place the parameters, along with the encoded page URL, into the API call below. The domain of the URL must match the domain under which the widget was created and must begin with `http://` or `https://`.

    Please note: The visitor's IP address and URL encoded user agent are only needed when the API call is made server-side.
servers:
  - url: api.content-ad.net/api.svc
    description: Widget API
paths:
  '/GetWidget/{Widet GUID}/{Domain ID}':
    get:
      summary: Get Widget Ads On-page
      tags:
        - GetWidget
      responses:
        '200':
          description: OK
        '':
          content:
            application/json:
              schema:
                type: object
                properties:
                  slot_count:
                    type: integer
                  styles:
                    type: string
                  articles:
                    type: array
                    items:
                      type: object
                      properties:
                        slot:
                          type: integer
                        url:
                          type: string
                        title:
                          type: string
                        image:
                          type: string
                        sponsored:
                          type: boolean
                      required:
                        - slot
                        - url
                        - title
                        - image
                        - sponsored
                required:
                  - slot_count
                  - articles
              examples:
                JSON:
                  value:
                    slot_count: 3
                    styles: '<style type="text/css" id="ac_xxxx_css"> #ac_xxxx { clear:both; display:block; text-align:left; margin:20px 0; position:relative; text-align:left; line-height:1em; }'
                    articles:
                      - slot: 1
                        url: 'http://example.content.ad/sample-url-here'
                        title: A Very Interesting Article You May Like
                        image: 'http://example.content.ad/sample-image.jpg'
                        sponsored: false
                      - slot: 2
                        url: 'http://example.content.ad/sample-url-here-2'
                        title: Another Interesting Article You May Like
                        image: 'http://example.content.ad/sample-image-2.jpg'
                        sponsored: true
                        sponsored_by: domain.com
                      - slot: 3
                        url: 'http://example.content.ad/sample-url-here-3'
                        title: Yet Another Interesting Article You May Like
                        image: 'http://example.content.ad/sample-image-3.jpg'
                        sponsored: true
                        sponsored_by: anotherdomain.com
      operationId: GetWidget
      description: The GetWidget endpoint will return either a JSON object containing ads.
      parameters:
        - schema:
            type: string
          in: query
          name: clientId
          description: |-
            Assigns a tracking parameter to clicks generated from the widget. Accepts any string up to 64 characters.
            The page URL's 'utm_source' value is stored here automatilally if a clientId value is not passed in.
            Note: The clientId must not include user-identifiable values.
        - schema:
            type: string
          in: query
          name: clientId2
          description: |-
            Assigns a tracking parameter to clicks generated from the widget. Accepts any string up to 64 characters.
            The page URL's 'utm_campaign' value is stored here automatilally if a clientId2 value is not passed in.
            Note: The clientId2 must not include user-identifiable values.
        - schema:
            type: string
          in: query
          name: pushId
          description: "Your Publisher provided subscriber ID. The 'pushId' value is treated interchangably with the 'euid' value. Default: none"
        - schema:
            type: string
          in: query
          name: euid
          description: "Your Publisher provided subscriber ID. The 'euid' value is treated interchangably with the 'pushId' value. Default: none"
        - schema:
            type: string
          in: query
          name: ipAddress
          description: "End user's IP Address. This is not the IP of your server, but instead the IP of the person who will receive the ad. This value is automaticaly filled for in-browser installation code (HTML response) requests. The visitor's IP address is required when the API call is made server-side."
          required: true
        - schema:
            type: string
          in: query
          name: userAgent
          description: "The URL encoded user agent string. This is not the user agent of your server, but instead the user agent string of the person who will receive the ad. This value is automaticaly filled for installation code (HTML response) requests. The visitor's URL encoded user agent are required when the API call is made server-side."
          required: true
        - schema:
            type: string
            example: 'true'
          in: query
          name: debug
          description: "If specified, the 'debug' and 'debugMode' parameters display reuest variables in the JSON and HTML responses, respecitively. Including this value in your request will return the debug data, reguardless of the value you assign to the parameter."
        - schema:
            type: string
            default: 'true'
            enum:
              - 'true'
              - 'false'
            example: 'false'
          in: query
          name: served
          description: "If true, records an impression for the widget. Value is automaticlay set to 'true' for installation code (HTML resonse) requests. If the request is for an auction, then the publisher must send a request with 'served=false', followed by a call to the user endpoint with 'served=true' to notify us that the bid was successful, and the ad was served. Default: true"
        - schema:
            type: string
            default: 'false'
            enum:
              - 'true'
              - 'false'
            example: 'true'
          in: query
          name: styles
          description: 'If true, returns CSS & JavaScript as part of the JSON response. CSS & JavaScript are always returned for HTML responses. Default: false'
        - schema:
            type: string
            example: callbackFunctionName
          in: query
          name: callback
          description: 'Wraps result set in function with provided name for JSONP compatiblitity. Default: null Expects: function name'
        - schema:
            type: string
          in: query
          name: ik
          description: Impression Key value. Expects UUID format
        - schema:
            type: string
          in: query
          name: url
          description: URL where the widget will be displayed. Must be URL Encoded.
          required: true
    parameters:
      - schema:
          type: string
        name: Widet GUID
        in: path
        required: true
        description: The GUID of your Content.ad widget.
      - schema:
          type: string
        name: Domain ID
        in: path
        required: true
        description: 'Your domain name in base64 encoded format. ex: `my.domain.com`'
  /widget/impression/served:
    post:
      summary: Bid Win
      tags:
        - User Endpoint
      responses:
        '200':
          description: OK
      operationId: servedEqualsTrue
      description: 'If `served=false` for the GetWidget call and the widget is then served by your software, then you MUST make a server side HTTP post request to update the impression to `served=true` by posting the vlaues in the `impression_served_url` received in the JSON response.'
      parameters:
        - schema:
            type: string
            default: 'true'
            enum:
              - 'true'
              - 'false'
            example: 'true'
          in: query
          name: served
          description: "If true, records an impression for the widget. Value is automaticlay set to 'true' for installation code (HTML resonse) requests. If the request was an auction, then the publisher must send a request with 'served=false', followed by a call to the user endpoint to notify us that the bid was successful, and the ad was served. Default: true"
          required: true
        - schema:
            type: string
          in: query
          name: ik
          description: Impression Key value. Look in the `impression_served_url` in the GetWidget JSON response object for the `ik` value. Expects UUID format
          required: true
        - schema:
            type: string
            example: '687719'
          in: query
          name: wid
          description: 'The unique identifier for your widget. Look in the `impression_served_url` in the GetWidget JSON response object for the `wid` value. Default: none'
          required: true
        - schema:
            type: string
          in: query
          name: haid
          description: Impression Key value. Look in the `impression_served_url` in the GetWidget JSON response object for the `haid` value.
          required: true
  /bidrequests:
    get:
      summary: Bid Requests
      tags:
        - Bid Requests
      responses: {}
      operationId: get-bidrequests
      description: ''
components:
  schemas: {}
  securitySchemes: {}
tags:
  - name: widget2
  - name: GetWidget
  - name: User Endpoint
  - name: Conversion Pixel
